CREATE TABLE boards (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(120) NOT NULL,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 CONSTRAINT chk_board_name CHECK (CHAR_LENGTH(TRIM(name)) > 0)
);
CREATE TABLE tasks (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 board_id BIGINT NOT NULL,
 title VARCHAR(200) NOT NULL,
 description TEXT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'TODO',
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
 CONSTRAINT fk_task_board FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE,
 CONSTRAINT chk_task_title CHECK (CHAR_LENGTH(TRIM(title)) > 0),
 CONSTRAINT chk_task_status CHECK (status IN ('TODO', 'IN_PROGRESS', 'DONE')),
 INDEX idx_tasks_board_status (board_id, status)
);
